/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CarStats = IDL.Record({
  'speed' : IDL.Nat,
  'acceleration' : IDL.Nat,
  'handling' : IDL.Nat,
});
export const CarType = IDL.Variant({
  'JET' : IDL.Null,
  'BASIC' : IDL.Null,
  'RACE' : IDL.Null,
  'HYPER' : IDL.Null,
  'STREET' : IDL.Null,
  'LIGHTNING' : IDL.Null,
  'SPORT' : IDL.Null,
});
export const CarInfo = IDL.Record({
  'unlockCost' : IDL.Nat,
  'stats' : CarStats,
  'carType' : CarType,
});
export const LeaderboardEntry = IDL.Record({
  'playerId' : IDL.Principal,
  'rank' : IDL.Nat,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'carType' : CarType,
});
export const PowerUpType = IDL.Variant({
  'FUEL_PACK' : IDL.Null,
  'SPEED_BOOST' : IDL.Null,
  'DOUBLE_COINS' : IDL.Null,
  'COIN_MAGNET' : IDL.Null,
  'TIME_SLOW' : IDL.Null,
  'INVINCIBILITY' : IDL.Null,
  'SHIELD' : IDL.Null,
});
export const PlayerProfilePublic = IDL.Record({
  'xp' : IDL.Nat,
  'selectedCar' : CarType,
  'playerId' : IDL.Principal,
  'coins' : IDL.Nat,
  'highScore' : IDL.Nat,
  'unlockedCars' : IDL.Vec(CarType),
  'powerUpLevels' : IDL.Vec(IDL.Tuple(PowerUpType, IDL.Nat)),
  'totalRaces' : IDL.Nat,
});
export const GameMode = IDL.Variant({ 'TIMED' : IDL.Null, 'SCORE' : IDL.Null });
export const MapTheme = IDL.Variant({
  'CITY' : IDL.Null,
  'CANYON' : IDL.Null,
  'HIGHWAY' : IDL.Null,
});
export const SubmitRaceInput = IDL.Record({
  'mode' : GameMode,
  'coinsCollected' : IDL.Nat,
  'distanceTravelled' : IDL.Nat,
  'score' : IDL.Nat,
  'mapTheme' : MapTheme,
  'carType' : CarType,
});

export const idlService = IDL.Service({
  'getCarCatalog' : IDL.Func([], [IDL.Vec(CarInfo)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getOrCreateProfile' : IDL.Func([], [PlayerProfilePublic], []),
  'getProfile' : IDL.Func([], [IDL.Opt(PlayerProfilePublic)], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getTotalPlayers' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalRaces' : IDL.Func([], [IDL.Nat], ['query']),
  'selectCar' : IDL.Func([CarType], [IDL.Bool], []),
  'submitRaceResult' : IDL.Func([SubmitRaceInput], [PlayerProfilePublic], []),
  'unlockCar' : IDL.Func([CarType], [IDL.Bool], []),
  'upgradePowerUp' : IDL.Func([PowerUpType], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CarStats = IDL.Record({
    'speed' : IDL.Nat,
    'acceleration' : IDL.Nat,
    'handling' : IDL.Nat,
  });
  const CarType = IDL.Variant({
    'JET' : IDL.Null,
    'BASIC' : IDL.Null,
    'RACE' : IDL.Null,
    'HYPER' : IDL.Null,
    'STREET' : IDL.Null,
    'LIGHTNING' : IDL.Null,
    'SPORT' : IDL.Null,
  });
  const CarInfo = IDL.Record({
    'unlockCost' : IDL.Nat,
    'stats' : CarStats,
    'carType' : CarType,
  });
  const LeaderboardEntry = IDL.Record({
    'playerId' : IDL.Principal,
    'rank' : IDL.Nat,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'carType' : CarType,
  });
  const PowerUpType = IDL.Variant({
    'FUEL_PACK' : IDL.Null,
    'SPEED_BOOST' : IDL.Null,
    'DOUBLE_COINS' : IDL.Null,
    'COIN_MAGNET' : IDL.Null,
    'TIME_SLOW' : IDL.Null,
    'INVINCIBILITY' : IDL.Null,
    'SHIELD' : IDL.Null,
  });
  const PlayerProfilePublic = IDL.Record({
    'xp' : IDL.Nat,
    'selectedCar' : CarType,
    'playerId' : IDL.Principal,
    'coins' : IDL.Nat,
    'highScore' : IDL.Nat,
    'unlockedCars' : IDL.Vec(CarType),
    'powerUpLevels' : IDL.Vec(IDL.Tuple(PowerUpType, IDL.Nat)),
    'totalRaces' : IDL.Nat,
  });
  const GameMode = IDL.Variant({ 'TIMED' : IDL.Null, 'SCORE' : IDL.Null });
  const MapTheme = IDL.Variant({
    'CITY' : IDL.Null,
    'CANYON' : IDL.Null,
    'HIGHWAY' : IDL.Null,
  });
  const SubmitRaceInput = IDL.Record({
    'mode' : GameMode,
    'coinsCollected' : IDL.Nat,
    'distanceTravelled' : IDL.Nat,
    'score' : IDL.Nat,
    'mapTheme' : MapTheme,
    'carType' : CarType,
  });
  
  return IDL.Service({
    'getCarCatalog' : IDL.Func([], [IDL.Vec(CarInfo)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getOrCreateProfile' : IDL.Func([], [PlayerProfilePublic], []),
    'getProfile' : IDL.Func([], [IDL.Opt(PlayerProfilePublic)], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getTotalPlayers' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalRaces' : IDL.Func([], [IDL.Nat], ['query']),
    'selectCar' : IDL.Func([CarType], [IDL.Bool], []),
    'submitRaceResult' : IDL.Func([SubmitRaceInput], [PlayerProfilePublic], []),
    'unlockCar' : IDL.Func([CarType], [IDL.Bool], []),
    'upgradePowerUp' : IDL.Func([PowerUpType], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };