/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CarInfo {
  'unlockCost' : bigint,
  'stats' : CarStats,
  'carType' : CarType,
}
export interface CarStats {
  'speed' : bigint,
  'acceleration' : bigint,
  'handling' : bigint,
}
export type CarType = { 'JET' : null } |
  { 'BASIC' : null } |
  { 'RACE' : null } |
  { 'HYPER' : null } |
  { 'STREET' : null } |
  { 'LIGHTNING' : null } |
  { 'SPORT' : null };
export type GameMode = { 'TIMED' : null } |
  { 'SCORE' : null };
export interface LeaderboardEntry {
  'playerId' : Principal,
  'rank' : bigint,
  'score' : bigint,
  'timestamp' : bigint,
  'carType' : CarType,
}
export type MapTheme = { 'CITY' : null } |
  { 'CANYON' : null } |
  { 'HIGHWAY' : null };
export interface PlayerProfilePublic {
  'xp' : bigint,
  'selectedCar' : CarType,
  'playerId' : Principal,
  'coins' : bigint,
  'highScore' : bigint,
  'unlockedCars' : Array<CarType>,
  'powerUpLevels' : Array<[PowerUpType, bigint]>,
  'totalRaces' : bigint,
}
export type PowerUpType = { 'FUEL_PACK' : null } |
  { 'SPEED_BOOST' : null } |
  { 'DOUBLE_COINS' : null } |
  { 'COIN_MAGNET' : null } |
  { 'TIME_SLOW' : null } |
  { 'INVINCIBILITY' : null } |
  { 'SHIELD' : null };
export interface SubmitRaceInput {
  'mode' : GameMode,
  'coinsCollected' : bigint,
  'distanceTravelled' : bigint,
  'score' : bigint,
  'mapTheme' : MapTheme,
  'carType' : CarType,
}
export interface _SERVICE {
  'getCarCatalog' : ActorMethod<[], Array<CarInfo>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getOrCreateProfile' : ActorMethod<[], PlayerProfilePublic>,
  'getProfile' : ActorMethod<[], [] | [PlayerProfilePublic]>,
  'getTopScores' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getTotalPlayers' : ActorMethod<[], bigint>,
  'getTotalRaces' : ActorMethod<[], bigint>,
  'selectCar' : ActorMethod<[CarType], boolean>,
  'submitRaceResult' : ActorMethod<[SubmitRaceInput], PlayerProfilePublic>,
  'unlockCar' : ActorMethod<[CarType], boolean>,
  'upgradePowerUp' : ActorMethod<[PowerUpType], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];