/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    playerId: Principal;
    rank: bigint;
    score: bigint;
    timestamp: bigint;
    carType: CarType;
}
export interface CarInfo {
    unlockCost: bigint;
    stats: CarStats;
    carType: CarType;
}
export interface SubmitRaceInput {
    mode: GameMode;
    coinsCollected: bigint;
    distanceTravelled: bigint;
    score: bigint;
    mapTheme: MapTheme;
    carType: CarType;
}
export interface CarStats {
    speed: bigint;
    acceleration: bigint;
    handling: bigint;
}
export interface PlayerProfilePublic {
    xp: bigint;
    selectedCar: CarType;
    playerId: Principal;
    coins: bigint;
    highScore: bigint;
    unlockedCars: Array<CarType>;
    powerUpLevels: Array<[PowerUpType, bigint]>;
    totalRaces: bigint;
}
export enum CarType {
    JET = "JET",
    BASIC = "BASIC",
    RACE = "RACE",
    HYPER = "HYPER",
    STREET = "STREET",
    LIGHTNING = "LIGHTNING",
    SPORT = "SPORT"
}
export enum GameMode {
    TIMED = "TIMED",
    SCORE = "SCORE"
}
export enum MapTheme {
    CITY = "CITY",
    CANYON = "CANYON",
    HIGHWAY = "HIGHWAY"
}
export enum PowerUpType {
    FUEL_PACK = "FUEL_PACK",
    SPEED_BOOST = "SPEED_BOOST",
    DOUBLE_COINS = "DOUBLE_COINS",
    COIN_MAGNET = "COIN_MAGNET",
    TIME_SLOW = "TIME_SLOW",
    INVINCIBILITY = "INVINCIBILITY",
    SHIELD = "SHIELD"
}
export interface backendInterface {
    getCarCatalog(): Promise<Array<CarInfo>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getOrCreateProfile(): Promise<PlayerProfilePublic>;
    getProfile(): Promise<PlayerProfilePublic | null>;
    getTopScores(): Promise<Array<LeaderboardEntry>>;
    getTotalPlayers(): Promise<bigint>;
    getTotalRaces(): Promise<bigint>;
    selectCar(carType: CarType): Promise<boolean>;
    submitRaceResult(input: SubmitRaceInput): Promise<PlayerProfilePublic>;
    unlockCar(carType: CarType): Promise<boolean>;
    upgradePowerUp(ptype: PowerUpType): Promise<boolean>;
}
import type { CarInfo as _CarInfo, CarStats as _CarStats, CarType as _CarType, GameMode as _GameMode, LeaderboardEntry as _LeaderboardEntry, MapTheme as _MapTheme, PlayerProfilePublic as _PlayerProfilePublic, PowerUpType as _PowerUpType, SubmitRaceInput as _SubmitRaceInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getCarCatalog(): Promise<Array<CarInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCarCatalog();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCarCatalog();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrCreateProfile(): Promise<PlayerProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateProfile();
                return from_candid_PlayerProfilePublic_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateProfile();
            return from_candid_PlayerProfilePublic_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<PlayerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopScores(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopScores();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopScores();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalPlayers(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalPlayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalPlayers();
            return result;
        }
    }
    async getTotalRaces(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalRaces();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalRaces();
            return result;
        }
    }
    async selectCar(arg0: CarType): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.selectCar(to_candid_CarType_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectCar(to_candid_CarType_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitRaceResult(arg0: SubmitRaceInput): Promise<PlayerProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRaceResult(to_candid_SubmitRaceInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PlayerProfilePublic_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRaceResult(to_candid_SubmitRaceInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PlayerProfilePublic_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlockCar(arg0: CarType): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockCar(to_candid_CarType_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockCar(to_candid_CarType_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async upgradePowerUp(arg0: PowerUpType): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradePowerUp(to_candid_PowerUpType_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradePowerUp(to_candid_PowerUpType_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CarInfo_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarInfo): CarInfo {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_CarType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarType): CarType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_LeaderboardEntry_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaderboardEntry): LeaderboardEntry {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerProfilePublic_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProfilePublic): PlayerProfilePublic {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PowerUpType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PowerUpType): PowerUpType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerProfilePublic]): PlayerProfilePublic | null {
    return value.length === 0 ? null : from_candid_PlayerProfilePublic_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    selectedCar: _CarType;
    playerId: Principal;
    coins: bigint;
    highScore: bigint;
    unlockedCars: Array<_CarType>;
    powerUpLevels: Array<[_PowerUpType, bigint]>;
    totalRaces: bigint;
}): {
    xp: bigint;
    selectedCar: CarType;
    playerId: Principal;
    coins: bigint;
    highScore: bigint;
    unlockedCars: Array<CarType>;
    powerUpLevels: Array<[PowerUpType, bigint]>;
    totalRaces: bigint;
} {
    return {
        xp: value.xp,
        selectedCar: from_candid_CarType_n4(_uploadFile, _downloadFile, value.selectedCar),
        playerId: value.playerId,
        coins: value.coins,
        highScore: value.highScore,
        unlockedCars: from_candid_vec_n11(_uploadFile, _downloadFile, value.unlockedCars),
        powerUpLevels: from_candid_vec_n12(_uploadFile, _downloadFile, value.powerUpLevels),
        totalRaces: value.totalRaces
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unlockCost: bigint;
    stats: _CarStats;
    carType: _CarType;
}): {
    unlockCost: bigint;
    stats: CarStats;
    carType: CarType;
} {
    return {
        unlockCost: value.unlockCost,
        stats: value.stats,
        carType: from_candid_CarType_n4(_uploadFile, _downloadFile, value.carType)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playerId: Principal;
    rank: bigint;
    score: bigint;
    timestamp: bigint;
    carType: _CarType;
}): {
    playerId: Principal;
    rank: bigint;
    score: bigint;
    timestamp: bigint;
    carType: CarType;
} {
    return {
        playerId: value.playerId,
        rank: value.rank,
        score: value.score,
        timestamp: value.timestamp,
        carType: from_candid_CarType_n4(_uploadFile, _downloadFile, value.carType)
    };
}
function from_candid_tuple_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_PowerUpType, bigint]): [PowerUpType, bigint] {
    return [
        from_candid_PowerUpType_n14(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FUEL_PACK: null;
} | {
    SPEED_BOOST: null;
} | {
    DOUBLE_COINS: null;
} | {
    COIN_MAGNET: null;
} | {
    TIME_SLOW: null;
} | {
    INVINCIBILITY: null;
} | {
    SHIELD: null;
}): PowerUpType {
    return "FUEL_PACK" in value ? PowerUpType.FUEL_PACK : "SPEED_BOOST" in value ? PowerUpType.SPEED_BOOST : "DOUBLE_COINS" in value ? PowerUpType.DOUBLE_COINS : "COIN_MAGNET" in value ? PowerUpType.COIN_MAGNET : "TIME_SLOW" in value ? PowerUpType.TIME_SLOW : "INVINCIBILITY" in value ? PowerUpType.INVINCIBILITY : "SHIELD" in value ? PowerUpType.SHIELD : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    JET: null;
} | {
    BASIC: null;
} | {
    RACE: null;
} | {
    HYPER: null;
} | {
    STREET: null;
} | {
    LIGHTNING: null;
} | {
    SPORT: null;
}): CarType {
    return "JET" in value ? CarType.JET : "BASIC" in value ? CarType.BASIC : "RACE" in value ? CarType.RACE : "HYPER" in value ? CarType.HYPER : "STREET" in value ? CarType.STREET : "LIGHTNING" in value ? CarType.LIGHTNING : "SPORT" in value ? CarType.SPORT : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CarInfo>): Array<CarInfo> {
    return value.map((x)=>from_candid_CarInfo_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CarType>): Array<CarType> {
    return value.map((x)=>from_candid_CarType_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_PowerUpType, bigint]>): Array<[PowerUpType, bigint]> {
    return value.map((x)=>from_candid_tuple_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaderboardEntry>): Array<LeaderboardEntry> {
    return value.map((x)=>from_candid_LeaderboardEntry_n7(_uploadFile, _downloadFile, x));
}
function to_candid_CarType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CarType): _CarType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_GameMode_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): _GameMode {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_MapTheme_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MapTheme): _MapTheme {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_PowerUpType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PowerUpType): _PowerUpType {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitRaceInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitRaceInput): _SubmitRaceInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mode: GameMode;
    coinsCollected: bigint;
    distanceTravelled: bigint;
    score: bigint;
    mapTheme: MapTheme;
    carType: CarType;
}): {
    mode: _GameMode;
    coinsCollected: bigint;
    distanceTravelled: bigint;
    score: bigint;
    mapTheme: _MapTheme;
    carType: _CarType;
} {
    return {
        mode: to_candid_GameMode_n21(_uploadFile, _downloadFile, value.mode),
        coinsCollected: value.coinsCollected,
        distanceTravelled: value.distanceTravelled,
        score: value.score,
        mapTheme: to_candid_MapTheme_n23(_uploadFile, _downloadFile, value.mapTheme),
        carType: to_candid_CarType_n17(_uploadFile, _downloadFile, value.carType)
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CarType): {
    JET: null;
} | {
    BASIC: null;
} | {
    RACE: null;
} | {
    HYPER: null;
} | {
    STREET: null;
} | {
    LIGHTNING: null;
} | {
    SPORT: null;
} {
    return value == CarType.JET ? {
        JET: null
    } : value == CarType.BASIC ? {
        BASIC: null
    } : value == CarType.RACE ? {
        RACE: null
    } : value == CarType.HYPER ? {
        HYPER: null
    } : value == CarType.STREET ? {
        STREET: null
    } : value == CarType.LIGHTNING ? {
        LIGHTNING: null
    } : value == CarType.SPORT ? {
        SPORT: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): {
    TIMED: null;
} | {
    SCORE: null;
} {
    return value == GameMode.TIMED ? {
        TIMED: null
    } : value == GameMode.SCORE ? {
        SCORE: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MapTheme): {
    CITY: null;
} | {
    CANYON: null;
} | {
    HIGHWAY: null;
} {
    return value == MapTheme.CITY ? {
        CITY: null
    } : value == MapTheme.CANYON ? {
        CANYON: null
    } : value == MapTheme.HIGHWAY ? {
        HIGHWAY: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PowerUpType): {
    FUEL_PACK: null;
} | {
    SPEED_BOOST: null;
} | {
    DOUBLE_COINS: null;
} | {
    COIN_MAGNET: null;
} | {
    TIME_SLOW: null;
} | {
    INVINCIBILITY: null;
} | {
    SHIELD: null;
} {
    return value == PowerUpType.FUEL_PACK ? {
        FUEL_PACK: null
    } : value == PowerUpType.SPEED_BOOST ? {
        SPEED_BOOST: null
    } : value == PowerUpType.DOUBLE_COINS ? {
        DOUBLE_COINS: null
    } : value == PowerUpType.COIN_MAGNET ? {
        COIN_MAGNET: null
    } : value == PowerUpType.TIME_SLOW ? {
        TIME_SLOW: null
    } : value == PowerUpType.INVINCIBILITY ? {
        INVINCIBILITY: null
    } : value == PowerUpType.SHIELD ? {
        SHIELD: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
